### PR TITLE
fix: add missing metadata for homepage (#676)

### LINKED ISSUE #676: Missing metadata for homepage in src/utils/metadata.js
Looking at the metadata.js, file , but there was no homepage entry 
Is homepage seo is generic ? 
Or if it is missing then i can add it in utils/metadata.js

### PR DESCRIPTION
**Pull request by RaginiSharma01**
Added the metadata for homePage in src/utils/metadata.js
this fix #676

### CODE REVIEW

**Comment by xmulligan** [comment]
Most of this has to do with netlify. Can you explain what that is doing?

**Comment by RaginiSharma01** [comment]
@xmulligan Yes sir so basically , my focus was on adding metaData for the homePage ,
but before adding this(metaData), i had just added a small fix for the netlify redirects .  Those redirect changes were not intentional.

Could you point me to which specific Netlify-related changes are concerning? I'd be happy to revert any accidental redirect modifications and keep only the intended SEO metadata improvements.

**Comment by xmulligan** [comment]
You are trying to add 3,000 lines of code and only 5 have to do with meta data so everything except src/utils/seo-metadata.js

**Comment by RaginiSharma01** [comment]
@xmulligan Yes i did it right this time ,Please do review it.
Also i had re-push it as DCO signof was required from my side.

File: src/utils/seo-metadata.js [hunk 1]
```diff
@@ -42,4 +46,4 @@ const newsletter = {
     'If you want to keep up on the latest in cloud native networking, observability, and security this is your source',
 };
 
-export { enterprise, learn, adopters, getHelp, getInvolved, tellingStory, newsletter, brand };
+export { enterprise, learn, adopters, getHelp, getInvolved, tellingStory, newsletter, brand,homepage };
```
Comment (xmulligan) [inline src/utils/seo-metadata.js:49]:
```suggestion
export { enterprise, learn, adopters, getHelp, getInvolved, tellingStory, newsletter, brand, homepage };
```

File: src/utils/seo-metadata.js [hunk 2]
```diff
@@ -1,10 +1,14 @@
 const enterprise = {
-  // title: 'Cilium - Enterprise Distributions & Training',
+  title: 'Cilium - Enterprise Distributions & Training Partners',
   description:
     'Learn how to get enterprise level support and training for Cilium from different vendors in the ecosystem',
 };
+const homepage = {
+  title: 'Cilium - eBPF-based Networking for Kubernetes',
+  description: 'Cilium provides eBPF-based networking, security policies, and observability for Kubernetes. Trusted by Google GKE, AWS EKS, and cloud native platforms worldwide.',
```
Comment (xmulligan) [inline src/utils/seo-metadata.js:8]:
```suggestion
  description: 'Cilium provides eBPF-based networking, observability, and security for Kubernetes and beyond. Trusted by all major cloud providers and cloud native platforms worldwide.',
```

**Review by xmulligan — APPROVED** [review]
